# Ameba configuration for cellwrap
# https://github.com/ameba-lang/ameba

# Enable/disable rules
Style/VerboseBlock:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/Formatting:
  Excluded:
    - "examples/*.cr"

Layout/TrailingBlankLines:
  Excluded:
    - "examples/*.cr"

# Customize rule parameters
Layout/EndOfLine:
  EnforcedStyle: lf

Layout/TrailingWhitespace:
  Enabled: true

Performance/FlattenOnce:
  Enabled: true

# Exclude files/directories
exclude:
  - "lib/"
  - ".beads/"
  - ".github/"
  - "examples/"